language: c
compiler:
    - clang
    - gcc

os:
    - linux
    - osx

script:
    - mkdir build
    - ./install-dependencies.bash
    - cd build && cmake ../  && cmake --build . && ctest --verbose .
